### ISSUE TITLE
Error using HDF5 1.10.2

### ISSUE THREAD

**Issue by yamadapc** [aldanor/hdf5-rs#18]
On macOS:
```
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 0:
  #000: H5P.c line 253 in H5Pcreate(): not a property list class
    major: Invalid arguments to routine
    minor: Inappropriate type
thread 'main' panicked at 'Failed to open hdf5 file: "Invalid property list id: -1"', libcore/result.rs:1009:5
```

**Comment by aldanor** [comment]
@yamadapc I know. This is due to int32->int64 hid_t breaking change in 1.10.0.

This has already been fixed in the [new branch](https://github.com/aldanor/hdf5-rs/tree/feature/2018) on all platforms (I've just got back to hacking on this crate a week ago after a year break and am planning to finish this time; so stay tuned).

**Comment by aldanor** [comment]
In the old version (master), there were no proper type bindings which I've spent considerable amount of time on the new branch.

Right now you could probably do something through the raw HDF5 C API, but that's what I'm working on right now (reading / writing datasets), planning to link it to `ndarray`. So, again, stay tuned because things get reshuffled right now, sorry about that :)

You can already see how it *will* work with types though ([`hdf5-derive` tests](https://github.com/aldanor/hdf5-rs/blob/feature/2018/hdf5-derive/tests/test.rs#L11)) through proc-macros.
